version: "3"
services:
  backend-service:
    container_name: lear-car-driving
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - "JAVA_OPTIONS=-XX:-OmitStackTraceInFastThrow -Dspring.profiles.active=local"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/learn-car-driving"
      - "SPRING_DATASOURCE_USERNAME=dbuser"
      - "SPRING_DATASOURCE_PASSWORD=12345"
    networks:
      - db-network
    restart: always

  database:
    image: postgres:14
    container_name: db
    hostname: db
    ports:
      - 127.0.0.1:5433:5432
    environment:
      - "POSTGRES_USER=dbuser"
      - "POSTGRES_PASSWORD=12345"
      - "POSTGRES_DB=learn-car-driving"
    networks:
      - db-network
    restart: always

networks:
  db-network: