spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/cong-chung
    username: postgres
    password: 12345
  sql:
    init:
      mode: always
