server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: should-be-override-from-env
    username: should-be-override-from-env
    password: should-be-override-from-env
  jackson:
    serialization:
      fail-on-empty-beans: false
  sql:
    init:
      mode: never
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: swagger-ui
    tags-sorter: alpha
    doc-expansion: none

app:
  jwt-secret: should-be-override-from-env
  jwt-expired: 3600 #minute